apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynginx
  namespace: test2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
